### 用户登录获取 token
@name login
@capture global.token from body.json.password
POST https://httpbingo.org/post
Content-Type: application/json

{
  "username": "rupost_user",
  "password": "secret_token_abc123"
}
