### 用户登录获取 token
@name login
@capture my_token from body.json.password
POST https://httpbin.org/post
Content-Type: application/json

{
  "username": "rupost_user",
  "password": "secret_token_abc123"
}
